"""add lazy select for tags and sources in note model

Revision ID: 1299ed74efc8
Revises: d5e964a4db5a
Create Date: 2025-08-11 14:40:51.400990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1299ed74efc8'
down_revision: Union[str, Sequence[str], None] = 'd5e964a4db5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
