"""add user_id column to set

Revision ID: 2eef19a06331
Revises: 89b8fbd00099
Create Date: 2025-08-23 20:50:29.218243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2eef19a06331'
down_revision: Union[str, Sequence[str], None] = '89b8fbd00099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_set_user_id'), 'set', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_user_id'), table_name='set')
    op.drop_column('set', 'user_id')
    # ### end Alembic commands ###
