"""rename set table

Revision ID: 32d4891e5c64
Revises: 665503f934a8
Create Date: 2025-08-07 15:37:35.449765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d4891e5c64'
down_revision: Union[str, Sequence[str], None] = '665503f934a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notes_set_id_fkey'), 'notes', type_='foreignkey')
    op.drop_column('notes', 'set_id')
    op.drop_index(op.f('ix_set_id'), table_name='sets')
    op.create_index(op.f('ix_sets_id'), 'sets', ['id'], unique=False)
    op.drop_constraint(op.f('sources_set_id_fkey'), 'sources', type_='foreignkey')
    op.drop_column('sources', 'set_id')
    op.drop_constraint(op.f('tags_set_id_fkey'), 'tags', type_='foreignkey')
    op.drop_column('tags', 'set_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tags_set_id_fkey'), 'tags', 'sets', ['set_id'], ['id'])
    op.add_column('sources', sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sources_set_id_fkey'), 'sources', 'sets', ['set_id'], ['id'])
    op.drop_index(op.f('ix_sets_id'), table_name='sets')
    op.create_index(op.f('ix_set_id'), 'sets', ['id'], unique=False)
    op.add_column('notes', sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notes_set_id_fkey'), 'notes', 'sets', ['set_id'], ['id'])
    # ### end Alembic commands ###
