"""add colors to models

Revision ID: 6fa47c2a5897
Revises: 8fedf0c7399e
Create Date: 2025-08-19 00:02:52.259597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fa47c2a5897'
down_revision: Union[str, Sequence[str], None] = '8fedf0c7399e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="yellow"))
    op.add_column('source', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="yellow"))
    op.add_column('tag', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="yellow"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'color')
    op.drop_column('source', 'color')
    op.drop_column('note', 'color')
    # ### end Alembic commands ###
