"""Add position column to note

Revision ID: 89b8fbd00099
Revises: 6fa47c2a5897
Create Date: 2025-08-22 15:22:29.552013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b8fbd00099'
down_revision: Union[str, Sequence[str], None] = '6fa47c2a5897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('position', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_note_position'), 'note', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_position'), table_name='note')
    op.drop_column('note', 'position')
    # ### end Alembic commands ###
