"""bring back foreign keys

Revision ID: a2e45626914d
Revises: 32d4891e5c64
Create Date: 2025-08-07 15:38:58.514591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2e45626914d'
down_revision: Union[str, Sequence[str], None] = '32d4891e5c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'sets', ['set_id'], ['id'])
    op.add_column('sources', sa.Column('set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sources', 'sets', ['set_id'], ['id'])
    op.add_column('tags', sa.Column('set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'sets', ['set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'set_id')
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'set_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'set_id')
    # ### end Alembic commands ###
